#!/usr/bin/env python3

import os
import argparse
import subprocess
import tempfile


parser = argparse.ArgumentParser(prog="wrapper for using mosh with assh")
parser.add_argument("host")

args = parser.parse_args()


# build a temp assh config with uncommmented HostName
ps = subprocess.Popen(["assh", "config", "build"], stdout=subprocess.PIPE)
output = subprocess.check_output(('sed', 's/# HostName:/HostName/'), stdin=ps.stdout)
ps.wait()


with tempfile.NamedTemporaryFile() as fp:
    fp.write(output)

    subprocess.check_call(["mosh", f"--ssh=ssh -F {fp.name}", args.host])
    # os.execvp("mosh", [__file__] + [f"--ssh=ssh -F {fp.name}", args.host])
